project_id: '1'
api_token: '${{ secrets.CROWDIN }}'
base_url: 'https://turingway.crowdin.com'
preserve_hierarchy: true
files:
  - source: /book/website/
    ignore:
      - LICENSE.md
      - _toc.yml
      - _config.yml
      - _redirects
      - /requirements.txt
      - runtime.txt
      - '*.png'
      - '*.jpg'
      - /_build/html
    translation: /book/translation/%three_letters_code%/%original_path%/%original_file_name%
